### PR TITLE
Added NbHits and ExhaustiveNbHits to SearchResult<T> object.

### LINKED ISSUE #109: SearchResult<T> is missing NbHits & ExhaustiveNbHits fields.
SearchResult<T> is missing NbHits & ExhaustiveNbHits fields. These are returned by the api but not mapped to the response object.

### PR DESCRIPTION
**Pull request by bzatrok**
Added NbHits and ExhaustiveNbHits to SearchResult<T> object. Currently these values are returned by the meilisearch api but not mapped to the SearchResutl object. Fixes #109

### CODE REVIEW

**Review by curquiza — APPROVED** [review]
Thanks a lot for this fix @bzatrok! :D

bors merge

**Comment by bzatrok** [comment]
My pleasure & much appreciated for the quick merge. Quick question: Are there any further steps we need to go through before this can be published as a new Nuget? Or you'll merge to master directly and fire off a build? :)

**Comment by curquiza** [comment]
I'm going to do the release right now 🙂

**Comment by curquiza** [comment]
Oh sorry I did not check you did the PR on `staging` instead of `main`, that's my fault! 
FYI, we do PR pointing to `main` (cf [this section](https://github.com/meilisearch/meilisearch-dotnet/blob/main/CONTRIBUTING.md#how-to-contribute) in the CONTRIBUTING)
I should have checked sorry!

**Comment by curquiza** [comment]
@bzatrok Could you do the same PR to `main` please? I cannot reopen the PR since it was merged

If you don't have the time, tell me, I will do it :)

**Comment by bzatrok** [comment]
Oh my bad, I assumed staging would be a step before you load it into the main branch. Pull request from the fork into main or staging->main ?

**Comment by curquiza** [comment]
That's our fault! We should be more explicit about how to do PRs!

**Pull request merged**
