### PR TITLE
Add Total tasks in task route

### LINKED ISSUE #462: [v1.3] Total Tasks in task route
⚠️ This issue is generated, it means the examples and the namings do not necessarily correspond to the language of this repository.
Also, if you are a maintainer, please add any clarification and instructions about this issue.

Sorry if this is already wholly/partially implemented. Feel free to let me know about the state of this issue in the repo.

Related to https://github.com/meilisearch/integration-guides/issues/280

----

### New implementation

Related to:
- spec: https://github.com/meilisearch/specifications/pull/253

Returns the total number of tasks matching the filters on the `GET /tasks` route.

Ensure the SDKs can handle the new get tasks response field `total`

TODO:
- [ ] Handle the response of the `getTasks` method by including the new attribute `total`

### PR DESCRIPTION
**Pull request by kashifsoofi**
# Pull Request

## Related issue
Fixes #462 

## What does this PR do?
- Added Total Tasks in task route

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
Thank you @kashifsoofi 

Can you add a test for this?

**Comment by kashifsoofi** [comment]
> Thank you @kashifsoofi
> 
> Can you add a test for this?

None of the other PRs adding this field has a test to check this field, maybe the server is not returing it?

**Comment by ahmednfwela** [comment]
@kashifsoofi this PR contains tests https://github.com/meilisearch/meilisearch-dart/pull/343

**Comment by curquiza** [comment]
Maybe we are missing tests about the other fields for this repo. In any case we need to add some 😊 
You can add tests in [this file](https://github.com/meilisearch/meilisearch-dotnet/blob/main/tests/Meilisearch.Tests/TaskInfoTests.cs)
Correct me if it's not the right file @ahmednfwela

**Comment by ahmednfwela** [comment]
yes tests can be added to this function https://github.com/meilisearch/meilisearch-dotnet/blob/d0193c43224235b25be1918eb2aa4ffa677aa484/tests/Meilisearch.Tests/TaskInfoTests.cs#L65-L71

**Review by brunoocasali — APPROVED** [review]
Thanks for your contribution! @kashifsoofi 🤘 

bors merge

**Comment by brunoocasali** [comment]
bors merge

**Pull request merged**
