### PR TITLE
Make the HTTP Client usage easier

### LINKED ISSUE #12: Make the usage easier
Make the package easy to use. The getting started should be:

```cs
Meilisearch ms = new Meilisearch("http://localhost:7700", "masterKey");
Index index = await ms.createIndex("books")
var updateStatus = await index.AddorUpdateDocuments(new[]{new  Movie {Id = "1", Name = "Batman"}});
```

🙂

### PR DESCRIPTION
**Pull request by satish860**
This PR contains the changes to make the Meilisearch easy to use.

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
Hello @satish860!

Thanks for this PR!

Some points:
- Can you fill the `Getting Started` section in the README, please? You can be inspired by what's been done in the other [meilisearch-dotnet repository](https://github.com/ndudnicz/meilisearch-dotnet) 🙂
- Can you update the docker command in the CI with `--master-key=masterKey` please?

**Comment by satish860** [comment]
@curquiza I have added the details on ReadMe and updated CI too.

**Review by curquiza — CHANGES_REQUESTED** [review]
Hello @satish860!

My feedback
- Can you remove the `.idea/.idea.Meilisearch/.idea/.name` file, please?
- You're branch is not up-to-date with `master` anymore, can you fix that, please? 🙂

**Comment by curquiza** [comment]
Sorry, I've just seen that: can you update the examples in `Examples` section please with the new usage of the MeilisearchClient? 🙂

**Review by curquiza — APPROVED** [review]

**Pull request merged**
