### PR TITLE
Client refactor with new api names for JSON format

### LINKED ISSUE #182: NDJSON/CSV methods to add and update documents
⚠️ This issue is generated, it means the nameing might be done differently in this package (ex: `add_documents_json` instead of `addDocumentsJson`). Keep the already existing way of naming in this package to stay idiomatic with the language and this repository.

📣 We strongly recommend doing multiple PRs to solve all the points of this issue

[MeiliSearch v0.23.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.23.1) introduces two changes:
- new valid formats to push data files, additionally to the JSON format: CSV and NDJSON formats.
- it enforces the `Content-type` header for every route requiring a payload (`POST` and `PUT` routes)

---

Here are the expected changes to completely close the issue:

- [x] Currently, the SDKs always send `Content-Type: application/json` to every request. Only the `POST` and `PUT` requests should send the `Content-Type: application/json` and not the `DELETE` and `GET` ones.

- [x] Add the following methods and 🔥 **the associated tests** 🔥 to ADD the documents. Depending on the format type (`csv` or `ndjson`) the SDK should send `Content-Type: application/x-dnjson` or `Content-Type: text/csv`)
  - [x] `addDocumentsJson(string docs, string primaryKey)`
  - [x] `addDocumentsCsv(string docs, string primaryKey)`
  - [x] `addDocumentsCsvInBatches(string docs, int batchSize, string primaryKey)`
  - [x] `addDocumentsNdjson(string docs, string primaryKey)`
  - [x] `addDocumentsNdjsonInBatches(string docs, int batchSize, string primaryKey)`

- [x] Add the following methods and 🔥 **the associated tests** 🔥 to UPDATE the documents. Depending on the format type (`csv` or `ndjson`) the SDK should send `Content-Type: application/x-dnjson` or `Content-Type: text/csv`)
  - [x] `updateDocumentsJson(string docs, string primaryKey)`
  - [x] `updateDocumentsCsv(string docs, string primaryKey)`
  - [x] `updateDocumentsCsvInBatches(string docs, int batchSize, string primaryKey)`
  - [x] `updateDocumentsNdjson(string docs, string primaryKey)`
  - [x] `updateDocumentsNdjsonInBatches(string docs, int batchSize, string primaryKey)`

`docs` are the documents sent as `String`
`primaryKey` is [the primary key of the index](https://docs.meilisearch.com/learn/core_concepts/indexes.html#primary-key)
`batchSize` is the size of the batch. Example: you can send 2000 documents in raw String in `docs` and ask for a `batchSize` of 1000, so your documents will be sent to MeiliSearch in two batches.

Example of PRs:
- in PHP SDK: https://github.com/meilisearch/meilisearch-php/pull/235
- in Python SDK: https://github.com/meilisearch/meilisearch-python/pull/329

----------

Related to: https://github.com/meilisearch/integration-guides/issues/146

If this issue is partially/completely implemented, feel free to let us know.

**EDIT**:

The files needed for the tests when creating the csv and ndjson methods are available here:
- [songs.csv](https://github.com/meilisearch/meilisearch-python/blob/main/datasets/songs.csv)
- [songs.ndjson](https://github.com/meilisearch/meilisearch-python/blob/main/datasets/songs.ndjson)

### PR DESCRIPTION
**Pull request by juchom**
# Pull Request

## What does this PR do?
This PR partially fixes #182 for JSON format

[BREAKING CHANGES]
`AddDocumentsAsync` is now `AddDocumentsJsonAsync`
`AddDocumentsInBatchesAsync` is now `AddDocumentsJsonInBatchesAsync`

`UpdateDocumentsAsync` is now `UpdateDocumentsJsonAsync`
`UpdateDocumentsInBatchesAsync` is now `UpdateDocumentsJsonInBatchesAsync`

The README and code samples have been updated to reflect the changes.

The test infrastructure has been updated to easily leverage it when we will add `NDJSON` and `CSV`.

I introduce a `JsonHttpContent`, this allow to remove some custom code from HttpExtensions (more will be removed later) and easily follow what Adding and Updating functions are doing.

Let me know if things are not clear, this PR is a bit big.

### CODE REVIEW

**Review by alallema — COMMENTED** [review]
Hi @juchom,
Thank you for this PR it is always a pleasure to have such good contributions! And sorry for the delay, I just got this SDK.
I had a couple of comments or questions first:
- the `AddDocuments` method is not destined to disappear only the specific functions (`json`, `csv`, `ndJson`) must be added
> (more will be removed later)
- Do you plan to add addDocument and other functions afterward?
Thanks again

**Comment by juchom** [comment]
Hi @alallema,

No problem for the delay, just take your time and do not hesitate to ask me questions if something is not clear.

I thought that `AddDocuments` method would disappear in favor of Json, Ndjson and Csv ones. 

What `AddDocuments` is supposed to do if we have support for the three formats ?

**Comment by juchom** [comment]
Ok, I went a bit fast, I've just checked the signature of the methods.

This is PR is not in line with the issue :) 

I will make new ones.

**Comment by alallema** [comment]
> What AddDocuments is supposed to do if we have support for the three formats?

The `AddDocuments` method is supposed to send an `Object`, `Class` or an `Array` according to the SDK, while the `AddDocumentsJson`, `AddDocumentsCsv` and `AddDocumentsNdJson` methods are supposed to retrieve this document in string format and send it as is.
To note: Before v0.23, all SDKs sent `Content-Type: application/json` on every request. After I added the possibility to send `NdJson` or `Csv` we left the sending of `Content-Yype` only for `POST` and `PUT` requests with the appropriate `Content-Type`. The `AddDocuments` method keep  `Content-Type: application/json` header.
Hope it's more clear, sorry maybe the issue isn't clear enough.

**Comment by juchom** [comment]
This is fine, I didn't check the methods signatures :)

**Pull request closed without merging**
