### PR TITLE
Adds some missing routes / features

### LINKED ISSUE #17: Missing routes need to be implemented
Some routes present in MeiliSearch are not implemented in this package yet:
- [X] The global settings routes: https://docs.meilisearch.com/references/settings.html
- [ ] The settings sub-routes: https://docs.meilisearch.com/references/settings.html
- [x] All the health routes: https://docs.meilisearch.com/references/health.html
- [x] The global stats route: https://docs.meilisearch.com/references/stats.html#get-stats-of-all-indexes
- [x] The index stats route: https://docs.meilisearch.com/references/stats.html#get-stat-of-an-index

The settings routes and sub-routes are the most urgent ones 🙂

⚠️ Tests should be added for each newly implemented route.

### PR DESCRIPTION
**Pull request by themisir**
Fixes #17

### CODE REVIEW

**Comment by themisir** [comment]
I think tests might need some changes because I think some tests might fail due to updates are async on meilisearch which conflicts with test cases (for example I'm updating settings then getting latest settings to check if it contains new values or not).

I have to merge some route tests for example I test Health routes on same test case by updating health and checking for `GetHealth` value. I'm doing same thing for Update / Reset / Get settings routes too.

**Comment by themisir** [comment]
```
  X Meilisearch.Tests.IndexTests.UpdateSettings [14ms]
  Error Message:
   System.NotSupportedException : The provided ContentType '' is not supported; the supported types are 'application/json' and the structured syntax suffix 'application/+json'.
  Stack Trace:
     at System.Net.Http.Json.HttpContentJsonExtensions.ValidateContent(HttpContent content)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsync[T](HttpContent content, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Meilisearch.Index.UpdateSettings(IndexSettings settings) in /home/runner/work/meilisearch-dotnet/meilisearch-dotnet/src/Meilisearch/Index.cs:line 249
   at Meilisearch.Tests.IndexTests.UpdateSettings() in /home/runner/work/meilisearch-dotnet/meilisearch-dotnet/tests/Meilisearch.Tests/IndexTests.cs:line 26
```

I don't know why doesn't this works. I think MeiliSearch is not responding to update settings request with json response (update status object).

[Update Settings](https://docs.meilisearch.com/references/settings.html#update-settings)

image

**Comment by curquiza** [comment]
Hello @TheMisir, as we discussed together on Slack, the PR #57 is finally merged!
You can remove your changes in relative to the settings `src/Meilisearch/Index.cs`, `src/Meilisearch/IndexSettings.cs` and `tests/Meilisearch.Tests/IndexTests.cs` 🙂

I will review your PR after that 🙂
Thanks again for your works on all these methods!! Really helpful!

**Comment by themisir** [comment]
> Hello @TheMisir, as we discussed together on Slack, the PR #57 is finally merged!
> You can remove your changes in relative to the settings `src/Meilisearch/Index.cs`, `src/Meilisearch/IndexSettings.cs` and `tests/Meilisearch.Tests/IndexTests.cs` 🙂
> 
> I will review your PR after that 🙂
> Thanks again for your works on all these methods!! Really helpful!

I have some non-coding related (life) problems, I'll continue working on this PR after fixing that problems in 1-2 days.

**Comment by curquiza** [comment]
Hello @TheMisir!
Take your time, not an emergency of course 😉 
I hope everything is gonna be ok in your non-coding life 🤞

**Comment by themisir** [comment]
🤦‍♂️ [pull](https://github.com/apps/pull) bot removed all the code I wrote by force-pushing. and I don't have local copy. So I have to start from beginning.

**Comment by curquiza** [comment]
Oh nooooo I'm so sorry for you! 🙁
Where does this bot come from?

If you don't want to do this issue after that, I would understand of course!

**Comment by themisir** [comment]
> Oh nooooo I'm so sorry for you! 🙁
> Where does this bot come from?
> 
> If you don't want to do this issue after that, I would understand of course!

Don't worry, I'm working on it. I'm closing this PR since it's empty, and will open a new PR when I made a progress.

**Pull request closed without merging**
