### PR TITLE
Distinct attribute at search time

### LINKED ISSUE #547: [v1.9] Accept `distinct` search parameter
*Following this [central issue](https://github.com/meilisearch/integration-guides/issues/301)*

This is related to a newly introduced feature in [Meilisearch v1.9.0](https://github.com/meilisearch/meilisearch/releases/tag/v1.9.0): use `distinct` search parameter.

Refer to [docs for more information](https://www.meilisearch.com/docs/reference/api/search#distinct-attributes-at-search-time).

- [ ] Ensure the library can accept the `distinct` search parameter.
- [ ] Add integration tests
- [ ] Update the `.code-samples.meilisearch.yaml`
    - [ ] Add `search_parameter_reference_distinct_1` key and “translate” the following curl example by using the newly added methods: https://github.com/meilisearch/documentation/blob/04f26a35771305378ed0a506f4d60ef06d07bd7e/.code-samples.meilisearch.yaml#L1308
    - [ ] Add `distinct_attribute_guide_filterable_1` key and “translate” the following curl example by using the newly added methods: https://github.com/meilisearch/documentation/blob/04f26a35771305378ed0a506f4d60ef06d07bd7e/.code-samples.meilisearch.yaml#L1316C1-L1316C38
    - [ ] Add `distinct_attribute_guide_distinct_parameter_1` key and “translate” the following curl example by using the newly added methods: https://github.com/meilisearch/documentation/blob/04f26a35771305378ed0a506f4d60ef06d07bd7e/.code-samples.meilisearch.yaml#L1325

### PR DESCRIPTION
**Pull request by zxcq544**
# Pull Request

## Related issue
Fixes #547

## What does this PR do?
- Adds `distinct` attribute at search time.
- Adds tests for `distinct` attribute at search time.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
hello @zxcq544 
Thank you for your PR

Two important things to fix before merging
- Not the full issue has been implemented. Can you implement the third point of the issue about code-samples?
- The test of our CI do not pass. Can you run them locally and fix them? The steps are described in [our CONTRIBUTING.md](https://github.com/meilisearch/meilisearch-dotnet/blob/main/CONTRIBUTING.md)

**Comment by zxcq544** [comment]
Done.

**Comment by zxcq544** [comment]
Fixed YAML linting. I think it's done now :)

**Review by curquiza — APPROVED** [review]
Thank youuu

bors merge

**Pull request merged**
