### PR TITLE
Remove JWT dependencies

### PR DESCRIPTION
**Pull request by juchom**
# Pull Request

## What does this PR do?
Avoid using a third party dependency for creating JWT. This also removes the transient dependency on Newtonsoft.Json which is affected by a security issue :

https://github.com/advisories/GHSA-5crp-9r3c-p9vr

## PR checklist
Please check if your PR fulfills the following requirements:
- [X] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [X] Have you read the contributing guidelines?
- [X] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by alallema — COMMENTED** [review]
Thanks, @juchom for this PR!
Look really nice but I know that we had to remove all the tests including the builder but can you add a check for `expiredAt` formatting? Maybe in the same way as for  `SearchesSuccessfullyWithTheNewToken`

**Comment by juchom** [comment]
Just to be clear you want a test with token that checks if we have an exception when the token is expired and a test that checks everything is fine when the expiry date is in the futur ?

**Comment by alallema** [comment]
> Just to be clear you want a test with token that checks if we have an exception when the token is expired and a test that checks everything is fine when the expiry date is in the future ?

Yes, I would like to have just one test that verifies that the `expiredAt` is formatted correctly because we had a lot of trouble with that don't need to test with an expired token except if you want to.

**Review by alallema — APPROVED** [review]
Thanks, @juchom for this PR!
LGTM!
And thanks for the tests addition 🔥

**Comment by alallema** [comment]
bors merge

**Comment by alallema** [comment]
_This message is sent automatically_

Thank you for contributing to Meilisearch. If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive some gift from Meilisearch too, please complete [this form](https://meilisearch.typeform.com/to/idt5qugY).

**Pull request merged**
