### PR TITLE
Implement dumps routes in .NET SDK

### LINKED ISSUE #69: Implement dumps
Since [v0.15.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.15.0), MeiliSearch exposes a new functionality: [dumps](https://docs.meilisearch.com/references/dump.html#dumps)

This feature should be implemented in this SDK following [this specificacions](https://github.com/meilisearch/integration-guides/issues/44)

- [ ] Implement dump creation route
- [ ] Implement get dump status route
- [ ] Add tests
<s>- [ ] Add code samples</s> not available for this SDK

### PR DESCRIPTION
**Pull request by AlexNDRmac**
- added Dumps model and routes
- added tests

#69 Implement dumps

### CODE REVIEW

**Comment by AlexNDRmac** [comment]
@eskombro, @curquiza  please check. Also, as for me... it'll be better if error handling will be better :) Maybe with MeiliSearch own Exception with all the exception details. It's just proposition :)

**Comment by curquiza** [comment]
Hello @AlexNDRmac! Thanks for this PR!
Yes, an error handler is clearly missing in this SDK, it's on my TODO, I will add it soon 😉
I'll check your PR at the beginning of the coming week. Thanks again for your contribution!!

**Comment by curquiza** [comment]
bors try

**Review by curquiza — APPROVED** [review]
Really nice! Thanks again for this contribution!

**Comment by curquiza** [comment]
bors merge

**Pull request merged**
