### PR TITLE
Refactor http client

### LINKED ISSUE #167: Refactor the way of handling HTTP request?
In https://github.com/meilisearch/meilisearch-dotnet/pull/165 I implemented an `HttpRequest` class to implement our own HTTP methods (`PostAsJsonAsync`...) to remove the `charset-utf8` content type.

However, I'm not a c# dev, and I feel like I missed something: at first I wanted to "extend" the `HttpClient` class and override `PostAsJsonAsync`, but without any success. So I came to the current implementation you can find in the `main` branch.

Does anyone know a better way to implement this?

Feel free to open any PR!

### PR DESCRIPTION
**Pull request by Vivek-abstract**
Refactoring as per issue:
https://github.com/meilisearch/meilisearch-dotnet/issues/167

I created a class for extension methods which will handle the custom extension methods like PostAsJsonAsync. Now we can use HttpClient directly and make requests.
I wasn't able to run the tests locally due to docker issues with hyper v. Let me know if any tests fail or if any other change is required. 

This is my first open source PR for .NET so let me know your feedback 😄

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
Hello @Vivek-abstract 

Thanks for your PR!

> I wasn't able to run the tests locally due to docker issues with hyper v. Let me know if any tests fail or if any other change is required.

You can also install and run MeiliSearch without docker, see [our docs](https://docs.meilisearch.com/learn/getting_started/installation.html#installation)

```bash
# Install MeiliSearch
curl -L https://install.meilisearch.com | sh

# Launch MeiliSearch
./meilisearch --master-key=masterKey
```

- The tests fail. You need to fix them to make the PR being merged :)
- The `HttpRequest.cs` file is still present. Is it expected?

**Comment by Vivek-abstract** [comment]
Thanks for the quick reply, I'll take a look at the failing tests. Regarding 2, we can remove the old HttpRequest

**Comment by Vivek-abstract** [comment]
@curquiza I've made the changes to make the tests pass. The method names for Post/Put were conflicting with the nuget package System.Net.Json so I changed the method name so it will pick our extension method instead of System.Net.Json. 

I managed to get the tests working and they are all passing locally. 😄

**Comment by curquiza** [comment]
bors try

**Review by curquiza — COMMENTED** [review]
Thanks for your changes @Vivek-abstract! 😄 

Can you
- remove the warning got during the build? :)
- can you change the name `...WithoutCharset...` by `Custom...`? We might want to add other customization in the future :)

**Comment by Vivek-abstract** [comment]
@curquiza I have fixed all the warnings and changed the method name to Custom. 😄

**Review by curquiza — APPROVED** [review]
Thank you!! 🙏 

bors merge

If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2021/), and you would like to receive a small gift from MeiliSearch too, please complete [this form](https://meilisearch.typeform.com/to/rPexR5gq).

**Pull request merged**
