### PR TITLE
Add methods to automatically add/update documents in batches

### LINKED ISSUE #157: Add methods to automatically add/update documents in batches
We need methods to add and update the documents of MeiliSearch in batch instead of letting the users call `addDocuments` in a loop.

- [ ] Add `addDocumentsInBatches`
```
addDocumentsInBatches(documents, batchSize = 1000, primaryKey = nil)
```
`batchSize` and `primaryKey` are optional parameters

- [ ] Add `updateDocumentsInBatches`
```
updateDocumentsInBatches(documents, batchSize = 1000, primaryKey = nil)
```
`batchSize` and `primaryKey` are optional parameters

- [ ] Add tests

Example: https://github.com/meilisearch/meilisearch-python/pull/260

⚠️ This issue is generated, it means `addDocumentsInBatches` andd `updateDocumentsInBatches` might be named differently in this package. Keep the already existing way of naming in this package to stay idiomatic with the language and the repository.
Also, if you are a maintainer, feel free to add any clarification and instruction about this issue related to the specific languages of the repo.

Related to https://github.com/meilisearch/integration-guides/issues/106

Sorry if this is already partially/completely implemented, feel free to let me know about the state of this issue in the repo.

### PR DESCRIPTION
**Pull request by alejandrocq**
Hi,

I have added the methods to add/update documents in batches (#157) in `Index.cs`. I have not been able to run the tests correctly because I get the following error in most of them:

```
Meilisearch.MeilisearchApiError
MeilisearchApiError, Message: The Content-Type "application/json; charset=utf-8" is invalid. Accepted values for the Content-Type header are: "application/json", "application/x-ndjson", "application/csv"
```

Seems to be an error with the `PostJsonAsync`method adding the charset parameter, but I suppose that has been working correctly for you.

Let me know if the code is okay and what should I do to fix that error. I will keep investigating if I get some time.

### CODE REVIEW

**Comment by curquiza** [comment]
Hello @alejandrocq

thanks a lot for your PR
You got an error because the repo was not up to date with the latest version of MeiliSearch. It is fixed now :)

**Review by curquiza — CHANGES_REQUESTED** [review]
Can you remove the warning during the build? :)

Capture d’écran 2021-10-13 à 14 02 53

At least the ones related to your PR.

**Comment by alejandrocq** [comment]
> Can you remove the warning during the build? :)
> 
> Capture d’écran 2021-10-13 à 14 02 53
> 
> At least the ones related to your PR.

Sure! I missed those. I will fix them.

**Comment by alejandrocq** [comment]
Ok, I think all it's alright now, at least build and test look good in my machine :)

**Review by curquiza — APPROVED** [review]
Thank you @alejandrocq 

bors merge

If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2021/), and you would like to receive a small gift from MeiliSearch too, please complete [this form](https://meilisearch.typeform.com/to/rPexR5gq).

**Comment by curquiza** [comment]
bors try

**Comment by curquiza** [comment]
oops looks like there are some flaky, I will open an issue (it's because of the dumps, so not related to your PR)
bors merge

**Pull request merged**
