### PR TITLE
Simplify construction of MeilisearchClient in DI

### PR DESCRIPTION
**Pull request by ahmednfwela**
# Pull Request

## Related issue
Fixes part of #481, which is the inability to use `.AddHttpMessageHandler<MeilisearchMessageHandler>()`

## What does this PR do?
- Adds default constructor for `MeilisearchMessageHandler`
- Refactor `MeilisearchClient` constructors to call one another, instead of redefining the logic in both.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by brunoocasali — APPROVED** [review]
Hey @ahmednfwela how can I check if this change does the trick?! 😬 

Is there a way to add tests or something? If not possible, let's merge anyway!

**Comment by ahmednfwela** [comment]
@brunoocasali The constructor change of `MeilisearchClient` is already covered by tests
and the `MeilisearchMessageHandler` constructor doesn't need tests, as long as it compiles.

**Comment by ahmednfwela** [comment]
We can add a new package to the repository to help with DI scenarios, that will be based on this comment https://github.com/meilisearch/meilisearch-dotnet/issues/481#issuecomment-1768386018.

**Comment by brunoocasali** [comment]
I don't think it is needed unless you say so! You can merge this if you want!

**Comment by ahmednfwela** [comment]
bors merge

**Pull request merged**
