### PR TITLE
fix nuget CI

### PR DESCRIPTION
**Pull request by ahmednfwela**
# Pull Request

## What does this PR do?
- fixes readme/logo path so it gets accepted by nuget CI
- https://github.com/meilisearch/meilisearch-dotnet/actions/runs/5520644971/jobs/10067885547#step:5:33

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ ] Have you read the contributing guidelines?
- [ ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

cc @alallema

### CODE REVIEW

**Comment by ahmednfwela** [comment]
changes can be tested by running `dotnet pack` locally

**Comment by alallema** [comment]
Thanks, @ahmednfwela ! I will remove the release, merge your PR, and re-release.
Sorry for the inconvenience

**Comment by ahmednfwela** [comment]
Thanks @alallema, all good 👍

**Review by alallema — APPROVED** [review]
LGTM! 🔥 
You're so efficient 😅

**Comment by alallema** [comment]
Let's go for the release again!

**Comment by ahmednfwela** [comment]
@alallema might be a good idea to add `dotnet pack` as an extra CI step here https://github.com/meilisearch/meilisearch-dotnet/blob/main/.github/workflows/tests.yml#L31-L32

**Comment by alallema** [comment]
@ahmednfwela, yes might be!
The Publish is still failing ... 🤔

**Comment by ahmednfwela** [comment]
well, dotnet pack worked, but it appears that your nuget API key might be outdated
ref https://github.com/meilisearch/meilisearch-dotnet/actions/runs/5520964221/jobs/10068369015#step:5:77

**Comment by alallema** [comment]
> well, dotnet pack worked, but it appears that your nuget API key might be outdated

Yes, I was just checking that. I don't have Nuget access I will find a new Key and try to relaunch the CI

**Comment by ahmednfwela** [comment]
it appears that @curquiza might have access, since he is registered as an owner

**Comment by alallema** [comment]
@ahmednfwela It's done! It's publish ☺️

**Pull request merged**
